/* Generated By:JJTree&JavaCC: Do not edit this line. JajaCodeConstants.java */
package fr.ufrst.m1info.projetcomp.m1comp2.analyser.jjc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JajaCodeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 5;
  /** RegularExpression Id. */
  int AINC = 6;
  /** RegularExpression Id. */
  int ALOAD = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int ASTORE = 9;
  /** RegularExpression Id. */
  int BOOLEEN = 10;
  /** RegularExpression Id. */
  int CST = 11;
  /** RegularExpression Id. */
  int CMP = 12;
  /** RegularExpression Id. */
  int DIV = 13;
  /** RegularExpression Id. */
  int ENTIER = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int GOTO = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int INC = 18;
  /** RegularExpression Id. */
  int INF = 19;
  /** RegularExpression Id. */
  int INIT = 20;
  /** RegularExpression Id. */
  int INVOKE = 21;
  /** RegularExpression Id. */
  int JCSTOP = 22;
  /** RegularExpression Id. */
  int LOAD = 23;
  /** RegularExpression Id. */
  int METH = 24;
  /** RegularExpression Id. */
  int MUL = 25;
  /** RegularExpression Id. */
  int NEG = 26;
  /** RegularExpression Id. */
  int NEWARRAY = 27;
  /** RegularExpression Id. */
  int NEW = 28;
  /** RegularExpression Id. */
  int NOP = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int POP = 32;
  /** RegularExpression Id. */
  int PUSH = 33;
  /** RegularExpression Id. */
  int RETURN = 34;
  /** RegularExpression Id. */
  int STORE = 35;
  /** RegularExpression Id. */
  int SUB = 36;
  /** RegularExpression Id. */
  int SUP = 37;
  /** RegularExpression Id. */
  int SWAP = 38;
  /** RegularExpression Id. */
  int TRUE = 39;
  /** RegularExpression Id. */
  int POINTVIRGULE = 40;
  /** RegularExpression Id. */
  int PAROUV = 41;
  /** RegularExpression Id. */
  int PARFERM = 42;
  /** RegularExpression Id. */
  int VIRGULE = 43;
  /** RegularExpression Id. */
  int VAR = 44;
  /** RegularExpression Id. */
  int VOID = 45;
  /** RegularExpression Id. */
  int WRITE = 46;
  /** RegularExpression Id. */
  int WRITELN = 47;
  /** RegularExpression Id. */
  int LENGTH = 48;
  /** RegularExpression Id. */
  int IDENTIFIER = 49;
  /** RegularExpression Id. */
  int NOMBRE = 50;
  /** RegularExpression Id. */
  int STRING = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"add\"",
    "\"ainc\"",
    "\"aload\"",
    "\"and\"",
    "\"astore\"",
    "\"booleen\"",
    "\"cst\"",
    "\"cmp\"",
    "\"div\"",
    "\"entier\"",
    "\"false\"",
    "\"goto\"",
    "\"if\"",
    "\"inc\"",
    "\"inf\"",
    "\"init\"",
    "\"invoke\"",
    "\"jcstop\"",
    "\"load\"",
    "\"meth\"",
    "\"mul\"",
    "\"neg\"",
    "\"newarray\"",
    "\"new\"",
    "\"nop\"",
    "\"not\"",
    "\"or\"",
    "\"pop\"",
    "\"push\"",
    "\"return\"",
    "\"store\"",
    "\"sub\"",
    "\"sup\"",
    "\"swap\"",
    "\"true\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"var\"",
    "\"void\"",
    "\"write\"",
    "\"writeln\"",
    "\"length\"",
    "<IDENTIFIER>",
    "<NOMBRE>",
    "<STRING>",
  };

}
