/* Generated By:JJTree: Do not edit this line. ASTJCSorte.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package fr.ufrst.m1info.projetcomp.m1comp2.ast.jjc;


import fr.ufrst.m1info.projetcomp.m1comp2.ast.commons.Nature;
import fr.ufrst.m1info.projetcomp.m1comp2.ast.mjj.VisitorException;

public
class ASTJCSorte extends SimpleNode {
  public ASTJCSorte(int id) {
    super(id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JajaCodeVisitor visitor, Object data) throws VisitorException {

    return
    visitor.visit(this, data);
  }

  public Nature getNature() {
    if(jjtGetValue() instanceof String){
      return Nature.fromString((String)jjtGetValue());
    }
    return (Nature) jjtGetValue();
  }
}
/* JavaCC - OriginalChecksum=d1b2cc0cd20969205405844594b07add (do not edit this line) */
