/* Generated By:JJTree: Do not edit this line. ASTJCIdent.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package fr.ufrst.m1info.projetcomp.m1comp2.ast.jjc;


import fr.ufrst.m1info.projetcomp.m1comp2.ast.mjj.VisitorException;

public
class ASTJCIdent extends SimpleNode {
  public ASTJCIdent(int id) {
    super(id);
  }

  private String ident;

  public void setValeur(String str){
    this.ident=str;
  }

  public String getValeur(){
    return this.ident;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JajaCodeVisitor visitor, Object data) throws VisitorException {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=913f1cf9421f973d7e5ea1c0f0659995 (do not edit this line) */
