/* Generated By:JJTree: Do not edit this line. ASTLoad.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package fr.ufrst.m1info.projetcomp.m1comp2.ast.jjc;


import fr.ufrst.m1info.projetcomp.m1comp2.ast.mjj.VisitorException;

public
class ASTLoad extends SimpleNode {
  public ASTLoad(int id) {
    super(id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JajaCodeVisitor visitor, Object data) throws VisitorException {

    return
    visitor.visit(this, data);
  }

    public String getIdent() {
      return (String) ((ASTJCIdent) jjtGetChild(0)).jjtGetValue();
    }
}
/* JavaCC - OriginalChecksum=d2284f7e9201af7b2581a5ebb9d8168e (do not edit this line) */
