/* Generated By:JJTree: Do not edit this line. ASTNewArray.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package fr.ufrst.m1info.projetcomp.m1comp2.ast.jjc;


import fr.ufrst.m1info.projetcomp.m1comp2.ast.commons.Type;
import fr.ufrst.m1info.projetcomp.m1comp2.ast.mjj.VisitorException;

public
class ASTNewArray extends SimpleNode {
  public ASTNewArray(int id) {
    super(id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JajaCodeVisitor visitor, Object data) throws VisitorException {

    return
    visitor.visit(this, data);
  }

  public String getIdent() {
    return (String) ((ASTJCIdent)jjtGetChild(0)).jjtGetValue();
  }

  public Type getType() {
    Object type = ((ASTJCType)jjtGetChild(1)).jjtGetValue();
    switch ((String) type) {
      case "entier": return Type.INTEGER;
      case "boolean": return Type.BOOLEAN;
    }
    return null;
  }
}
/* JavaCC - OriginalChecksum=0fbde2a755fa86a3bf41444012468283 (do not edit this line) */
