/* Generated By:JavaCC: Do not edit this line. JajaCodeTreeConstants.java Version 7.0.12 */
package fr.ufrst.m1info.projetcomp.m1comp2.ast.jjc;


public interface JajaCodeTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTJAJACODE = 2;
  public int JJTJCNIL = 3;
  public int JJTINIT = 4;
  public int JJTSWAP = 5;
  public int JJTNEW = 6;
  public int JJTNEWARRAY = 7;
  public int JJTINVOKE = 8;
  public int JJTRETURN = 9;
  public int JJTWRITE = 10;
  public int JJTWRITELN = 11;
  public int JJTPUSH = 12;
  public int JJTPOP = 13;
  public int JJTLOAD = 14;
  public int JJTALOAD = 15;
  public int JJTSTORE = 16;
  public int JJTASTORE = 17;
  public int JJTIF = 18;
  public int JJTGOTO = 19;
  public int JJTINC = 20;
  public int JJTAINC = 21;
  public int JJTLENGTH = 22;
  public int JJTNOP = 23;
  public int JJTJCSTOP = 24;
  public int JJTJCIDENT = 25;
  public int JJTJCTYPE = 26;
  public int JJTJCSORTE = 27;
  public int JJTNEG = 28;
  public int JJTNOT = 29;
  public int JJTADD = 30;
  public int JJTSUB = 31;
  public int JJTMUL = 32;
  public int JJTDIV = 33;
  public int JJTCMP = 34;
  public int JJTSUP = 35;
  public int JJTINF = 36;
  public int JJTOR = 37;
  public int JJTAND = 38;
  public int JJTJCNBRE = 39;
  public int JJTJCVRAI = 40;
  public int JJTJCFAUX = 41;
  public int JJTJCSTRING = 42;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "JajaCode",
    "JCNil",
    "Init",
    "Swap",
    "New",
    "NewArray",
    "Invoke",
    "Return",
    "Write",
    "Writeln",
    "Push",
    "Pop",
    "Load",
    "ALoad",
    "Store",
    "AStore",
    "If",
    "Goto",
    "Inc",
    "AInc",
    "Length",
    "Nop",
    "JCStop",
    "JCIdent",
    "JCType",
    "JCSorte",
    "Neg",
    "Not",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Cmp",
    "Sup",
    "Inf",
    "Or",
    "And",
    "JCNbre",
    "JCVrai",
    "JCFaux",
    "JCString",
  };
}
/* JavaCC - OriginalChecksum=b2a67bf7589ba5f0520923c50578234f (do not edit this line) */
