/* Generated By:JavaCC: Do not edit this line. MiniJajaTreeConstants.java Version 7.0.12 */
package fr.ufrst.m1info.projetcomp.m1comp2.ast.mjj;

public interface MiniJajaTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCLASSE = 1;
  public int JJTIDENT = 2;
  public int JJTVOID = 3;
  public int JJTDECLS = 4;
  public int JJTVNIL = 5;
  public int JJTCST = 6;
  public int JJTTABLEAU = 7;
  public int JJTMETHODE = 8;
  public int JJTVAR = 9;
  public int JJTVARS = 10;
  public int JJTVEXP = 11;
  public int JJTOMEGA = 12;
  public int JJTMAIN = 13;
  public int JJTENTETES = 14;
  public int JJTENIL = 15;
  public int JJTENTETE = 16;
  public int JJTINSTRS = 17;
  public int JJTINIL = 18;
  public int JJTRETOUR = 19;
  public int JJTECRIRE = 20;
  public int JJTECRIRELN = 21;
  public int JJTSI = 22;
  public int JJTTANTQUE = 23;
  public int JJTAPPELI = 24;
  public int JJTTAB = 25;
  public int JJTAFFECTATION = 26;
  public int JJTSOMME = 27;
  public int JJTINCREMENT = 28;
  public int JJTLISTEXP = 29;
  public int JJTEXNIL = 30;
  public int JJTNON = 31;
  public int JJTNEG = 32;
  public int JJTET = 33;
  public int JJTOU = 34;
  public int JJTEGAL = 35;
  public int JJTINF = 36;
  public int JJTSUP = 37;
  public int JJTPLUS = 38;
  public int JJTMOINS = 39;
  public int JJTMULT = 40;
  public int JJTDIV = 41;
  public int JJTLONGUEUR = 42;
  public int JJTVRAI = 43;
  public int JJTFAUX = 44;
  public int JJTAPPELE = 45;
  public int JJTNBRE = 46;
  public int JJTRIEN = 47;
  public int JJTENTIER = 48;
  public int JJTBOOLEEN = 49;
  public int JJTCHAINE = 50;


  public String[] jjtNodeName = {
          "Start",
          "classe",
          "ident",
          "void",
          "decls",
          "vnil",
          "cst",
          "tableau",
          "methode",
          "var",
          "vars",
          "vexp",
          "omega",
          "main",
          "entetes",
          "enil",
          "entete",
          "instrs",
          "inil",
          "retour",
          "ecrire",
          "ecrireln",
          "si",
          "tantque",
          "appelI",
          "tab",
          "affectation",
          "somme",
          "increment",
          "listexp",
          "exnil",
          "non",
          "neg",
          "et",
          "ou",
          "egal",
          "inf",
          "sup",
          "plus",
          "moins",
          "mult",
          "div",
          "longueur",
          "vrai",
          "faux",
          "appelE",
          "nbre",
          "rien",
          "entier",
          "booleen",
          "chaine",
  };
}
/* JavaCC - OriginalChecksum=affd9c722dc73b3ee52426c5613d4225 (do not edit this line) */
