/* Generated By:JavaCC: Do not edit this line. MiniJajaDefaultVisitor.java Version 7.0.12 */
package fr.ufrst.m1info.projetcomp.m1comp2.ast.mjj;

public class MiniJajaDefaultVisitor implements MiniJajaVisitor{
  public Object defaultVisit(SimpleNode node, Object data) throws VisitorException {
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTclasse node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTident node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTdecls node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTvnil node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTcst node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTtableau node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTmethode node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTvar node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTvars node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTvexp node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTomega node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTmain node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTentetes node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTenil node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTentete node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTinstrs node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTinil node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTinstr node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTretour node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTecrire node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTecrireln node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTsi node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTtantque node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTappelI node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTtab node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTaffectation node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTsomme node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTincrement node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTlistexp node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTexnil node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTnon node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTneg node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTet node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTou node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTegal node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTinf node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTsup node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTplus node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTmoins node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTmult node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTdiv node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTlongueur node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTvrai node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTfaux node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTappelE node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTnbre node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTrien node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTentier node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTbooleen node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
  public Object visit(ASTchaine node, Object data) throws VisitorException {
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=7b334daab31d3bcbbf3f3973bbc11feb (do not edit this line) */
