/* Generated By:JJTree&JavaCC: Do not edit this line. MiniJajaConstants.java */
package fr.ufrst.m1info.projetcomp.m1comp2.analyser.mjj;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJajaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 7;
  /** RegularExpression Id. */
  int FINAL = 8;
  /** RegularExpression Id. */
  int MAIN = 9;
  /** RegularExpression Id. */
  int RETURN = 10;
  /** RegularExpression Id. */
  int WRITE = 11;
  /** RegularExpression Id. */
  int WRITELN = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int LENGTH = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int LBRACE = 19;
  /** RegularExpression Id. */
  int RBRACE = 20;
  /** RegularExpression Id. */
  int SEMICOLON = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int LPAR = 23;
  /** RegularExpression Id. */
  int RPAR = 24;
  /** RegularExpression Id. */
  int LBRACKET = 25;
  /** RegularExpression Id. */
  int RBRACKET = 26;
  /** RegularExpression Id. */
  int EQ = 27;
  /** RegularExpression Id. */
  int ASSIGN = 28;
  /** RegularExpression Id. */
  int BANG = 29;
  /** RegularExpression Id. */
  int INCR = 30;
  /** RegularExpression Id. */
  int PLUSASSIGN = 31;
  /** RegularExpression Id. */
  int PLUS = 32;
  /** RegularExpression Id. */
  int MINUS = 33;
  /** RegularExpression Id. */
  int STAR = 34;
  /** RegularExpression Id. */
  int SLASH = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int AND = 37;
  /** RegularExpression Id. */
  int GT = 38;
  /** RegularExpression Id. */
  int LT = 39;
  /** RegularExpression Id. */
  int QUOTE = 40;
  /** RegularExpression Id. */
  int VOID = 41;
  /** RegularExpression Id. */
  int INT = 42;
  /** RegularExpression Id. */
  int BOOLEAN = 43;
  /** RegularExpression Id. */
  int NOMBRE = 44;
  /** RegularExpression Id. */
  int STRING = 45;
  /** RegularExpression Id. */
  int IDENT = 46;
  /** RegularExpression Id. */
  int LETTER = 47;
  /** RegularExpression Id. */
  int DIGIT = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"class\"",
    "\"final\"",
    "\"main\"",
    "\"return\"",
    "\"write\"",
    "\"writeln\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"==\"",
    "\"=\"",
    "\"!\"",
    "\"++\"",
    "\"+=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"||\"",
    "\"&&\"",
    "\">\"",
    "\"<\"",
    "\"\\\"\"",
    "\"void\"",
    "\"int\"",
    "\"boolean\"",
    "<NOMBRE>",
    "<STRING>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
  };

}
